BOT_NAME = "RPA_FINANCEIRO_01"
MAX_RETRIES = 3
EXECUTION_TIMEOUT = 30.0
IS_PRODUCTION = False

print(BOT_NAME)
print(type(BOT_NAME))

print(MAX_RETRIES)
print(type(MAX_RETRIES))

print(EXECUTION_TIMEOUT)
print(type(EXECUTION_TIMEOUT))

print(IS_PRODUCTION)
print(type(IS_PRODUCTION))
